[book]
authors = ["<Adeoye Adefemi adefemiadeoye@yahoo.com>"]
language = "en"
multilingual = false
src = "docs/src"
title = "racoon"

[output.html]
default-theme = "light"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/opeolluwa/molybdenum"
input-404 = "not-found.md"